### PR TITLE
Parse the commands for the compiler more correctly

### PR DESCRIPTION
**Pull request by marcelhollerbach**
This adresses the first two problems described in #40

### CODE REVIEW

**Comment by pfultz2** [comment]
Thanks for the request, but this excludes lots of necessary flags. The parsing should instead properly group the `-c` flag arguments to make it easier to exclude(and also the `flags_to_merge` variable would become unnecessary).

Of course, I haven't ran into a problem with a compiler put flags after `-c`, have you seen this?

**Comment by marcelhollerbach** [comment]
Hi, which line changes do you mean?

My Problem I was seeing is that cmake put all flags behind a -c so the arguments have never been passed to clang ...

**Comment by pfultz2** [comment]
> Hi, which line changes do you mean?

I mean this line [here](https://github.com/pfultz2/ClangComplete/blob/develop/clangcomplete.py#L76). Instead of just merging the flags that are listed in `flags_to_merge`, it should merge all flags, but this would require a little refactoring so it works correctly, but it will make it easier to filter out the `-c` flag.

**Comment by marcelhollerbach** [comment]
Aaah, ok, so your idea is to just filter in ```merge_flags``` ?

I am okay with that. But I dont understand why you want to keep the flags with -m,-arch and -pthread. I am also not that sure if the module needs to do this filtering at all. I mean, clang is going to use the options which are needed, it does not create a executable, so all the linker options can be passed, but will never be used, maybe this solves alot of those problems, if we are just passing all options we are getting.

**Comment by pfultz2** [comment]
It only parses the flags for compilation only(from cmake's `CXX_FLAGS` or from the compile_commands.json). There are no linker options that are passed. Flags such as -m,-arch and -pthread are needed for compilation and can obviously cause incorrect diagnostic errors in sublime if omitted.

**Comment by pfultz2** [comment]
Also, i pushed a changed on develop that should fix this. Let me know how that works.

**Pull request closed without merging**
